### ISSUE TITLE
Content-Length is removed by Cloudflare and results in an error.

### ISSUE THREAD

**Issue by shine-star** [renpy/renpy-build#75]
When using Cloudflare, Content-Length in the response header is removed.
Therefore, retrieving the response header of the zip file will fail.
This is a Cloudfrare specification; even if Content-Length is set, it will be removed.

https://github.com/renpy/renpy-build/blob/master/runtime/web/renpy-pre.js#L357

If Content-Length is undefined, the variable will be NaN. Finally, `statusProgress.max = total;` assigns NaN, which results in an error.

https://github.com/renpy/renpy-build/blob/master/runtime/web/renpy-pre.js#L192
![image](https://github.com/renpy/renpy-build/assets/13634523/60558e8d-92ca-4a76-af22-f5aa638b1f83)

Thank you.

**Comment by Kassy2048** [comment]
> This is a Cloudfrare specification; even if Content-Length is set, it will be removed.

AFAIK, Cloudflare only removes the Content-Length header when it compresses the response body. It should not do that for content that is already compressed though (ZIP or PNG files for instance), and I've checked on my own servers that it does not. So maybe you should make sure your Web server returns the correct Content-Type header based on files extension and/or content so that Cloudflare knows if it's worth to compress the response or not? Or maybe this is your origin server that does the compression?

Anyway, you're right, there's a bug in Ren'Py and that's being fixed.

**Comment by shine-star** [comment]
We were using php to generate the zip files which are stored on a separate server.
The URL is *.zip and the output is the program.

You are correct, by removing the X-Powered-By and Content-Encoding:gzip response headers, Cloudflare now also adds a Content-Length response header.

Great support, thank you!
